language: python
sudo: true
os:
  - linux
  - osx
python:
    - "2.7"
services:
  - docker
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash travis-linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo bash travis-osx.sh; fi
after_success:
  - coveralls
before_deploy:
  - export RELEASE_PKG_FILE=$(ls dist/openbazaard*)
deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file:
      - dist/openbazaard-linux32
      - dist/openbazaard-linux64
      - dist/openbazaard-windows32.exe
      - dist/openbazaard-windows64.exe
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file:
      - dist/openbazaard-osx
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_OS_NAME = osx
